Use wrapped error that includes path
ririsoft/async-walkdir pull request #7
Opened 2024-03-28 03:55 UTC by jdanford

Closes #3

2024-03-28 12:03 UTC, ririsoft requested changes
Hello @jdanford ,

Thank you very much for your proposal, this will allow to close a long standing issue.
I added a few comments to the code review, with some required changes and open questions where your feedback would be appreciated.

Thank you very much in advance !

2024-03-28 12:03 UTC, ririsoft commented on Cargo.toml
> +version = "1.1.0"
I believe the change requires a major version bump: we are replacing the previous error type `std::io::Error` by another one which is not binary compatible. (see https://doc.rust-lang.org/cargo/reference/semver.html#item-remove)

2024-03-28 12:03 UTC, ririsoft commented on src/error.rs
> +use std::{
Can you had a copyright & license header please ?
For instance :

```rust
// SPDX-FileCopyrightText: 2020-2024 Ririsoft <riri@ririsoft.com>
// SPDX-FileCopyrightText: 2024 Your whatever name/nickname <your whatever mail>
// SPDX-License-Identifier: Apache-2.0
```

2024-03-28 12:03 UTC, ririsoft commented on src/error.rs
> +#[derive(Debug)]
What about using [thiserror](https://docs.rs/thiserror/latest/thiserror/) ?
We could have something like :

```rust
#[derive(Error, Debug)]
pub enum Error {
    #[error("IO error at '{path}': {}")]
    Io {
        path: PathBuf,
        #[from]
        source: io::Error,
    },
}
```

PROs: We are massively simplifying the code.
CONs: We are adding a dependency on `thiserror`, not big deal to me as it is a quiet standard pattern.

2024-03-28 12:05 UTC, ririsoft commented
Also can you format the code with `cargo fmt` so that the CI/CD runs OK ?

2024-03-28 16:00 UTC, jdanford commented
Alright, made all those changes. Using `thiserror` sounds fine, it's your project so I'll let you make that call.

2024-04-02 09:08 UTC, ririsoft commented
Hello @jdanford, I pushed to your branch a new version using [`thiserror` ](https://docs.rs/thiserror/latest/thiserror/index.html). Does it matches your expectations ?

2024-04-02 14:33 UTC, jdanford commented
Works for me!

2024-04-02 14:37 UTC, ririsoft approved these changes

2024-04-02 14:40 UTC, merged

2024-04-02 14:42 UTC, ririsoft commented
Thank you @jdanford for your contribution. I will release soon, once I also close #4.